version: '3.5'

services:
  go-work-app:
    build: .
    depends_on:
      - postgres
    environment:
      POSTGRES_APP_PASSWORD: ${POSTGRES_APP_PASSWORD}
    entrypoint:
      - "./wait-for"
      - "postgres:5432"
      - "--"
      - "./go-work"
      - "--server-port"
      - "8080"
      - "--db-host"
      - "postgres"
      - "--interval" #SCHEDULER PING INTERVALS START
      - "1"
      - "--interval"
      - "2"          #SCHEDULER PING INTERVALS END
    ports:
      - "${APP_SERVER_PORT:-8080}:8080"

  postgres:
    build: build/postgres
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
      POSTGRES_APP_PASSWORD: ${POSTGRES_APP_PASSWORD}
      POSTGRES_DB: "go-work"
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin

    ports:
      - "${PGADMIN_PORT:-5050}:80"
    restart: unless-stopped

volumes:
  postgres:
  pgadmin: