name: Build and test go-work

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Download dependencies
        run: go mod download

      - name: Build main executable
        run: go build -v cmd/go-work/main.go

      - name: Start environment
        run: docker compose up -d
        env:
          POSTGRES_ADMIN_PASSWORD: admin_password
          POSTGRES_APP_PASSWORD: app_password

      - name: Test application
        run: go test -v
        env:
          TEST_DB_HOST: localhost
          TEST_DB_PORT: 5432
          TEST_DB_PASSWORD: app_password
